-- AlterTable
ALTER TABLE "game_players" ADD COLUMN     "bazasGanadas" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cantes20" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cantes40" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "eloAfter" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "eloBefore" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "totalPuntos" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "tutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "vecesIrADos" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "games" ADD COLUMN     "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "elo" INTEGER NOT NULL DEFAULT 1000;
